train_id: no1
load_checkpoint: None

# dataset
rootdir: ./dataset
dataset: MyData
num_classes: 2
val_fold: None
test_fold: None

# train
trainer: BaseTrainer
optimizer: RMSprop
batch_size: 64
num_epochs: 50
ckpt_freq: 1
ckpt: None
learning_rate: 0.0002
weight_decay: 0.0
loss_type: CrossEntropy

# model (stage 1: ArcNN feature extractor)
model: ArcNN
ArcNN:
  num_inputs: 1
  dropout: 0.2